"""
Document text extraction module.

Responsible for converting uploaded files (PDF, TXT) into clean plain text.
This module is called by the upload route AFTER the file has been saved to disk.

Supports:
  - PDF  → PyMuPDF (fitz) — reads embedded text layer
  - TXT  → direct file read
  - DOCX → placeholder for future extension

Architecture:
  extract_text()                 ← public entry point (routes call this)
      ├── extract_text_from_pdf()    ← PDF-specific logic
      ├── extract_text_from_txt()    ← TXT-specific logic
      └── _clean_text()              ← shared post-processing
"""

from __future__ import annotations

import re
from pathlib import Path

import fitz  # PyMuPDF — installed as "PyMuPDF", imported as "fitz"


# ═══════════════════════════════════════════════════════════════════════════
# PUBLIC API
# ═══════════════════════════════════════════════════════════════════════════


def extract_text(file_path: Path, content_type: str) -> tuple[str, list[str], int]:
    """
    Main entry point — routes to the correct extractor based on MIME type.

    Args:
        file_path:    Path to the file saved on disk (in data/uploads/).
        content_type: MIME type string from the upload request.

    Returns:
        A tuple of three values:
          - full_text  (str):       All pages joined into one string.
          - pages      (list[str]): Each page's text as a separate string.
          - page_count (int):       Total number of pages.

    Raises:
        ValueError: If content_type is not supported.

    Example:
        >>> text, pages, count = extract_text(Path("denial.pdf"), "application/pdf")
        >>> print(count)
        1
        >>> print(text[:50])
        'AcmeCare Health Insurance Claims Processing ...'
    """
    if content_type == "application/pdf":
        return extract_text_from_pdf(file_path)
    elif content_type == "text/plain":
        return extract_text_from_txt(file_path)
    else:
        raise ValueError(
            f"Unsupported content type: '{content_type}'. "
            f"Supported types: application/pdf, text/plain"
        )


# ═══════════════════════════════════════════════════════════════════════════
# FORMAT-SPECIFIC EXTRACTORS
# ═══════════════════════════════════════════════════════════════════════════


def extract_text_from_pdf(file_path: Path) -> tuple[str, list[str], int]:
    """
    Extract text from a PDF using PyMuPDF.

    How PyMuPDF works:
      1. fitz.open() loads the PDF into memory
      2. We iterate over each page object
      3. page.get_text() returns the text layer for that page
      4. We collect all pages, then join them with double-newlines

    Our synthetic denial PDFs (generated by fpdf) have embedded text —
    they are NOT scanned images. So get_text() works perfectly.
    For scanned PDFs, you'd need OCR (pytesseract) — out of scope for now.

    Args:
        file_path: Path to the PDF file.

    Returns:
        (full_text, per_page_texts, page_count)
    """
    # Open the PDF document
    doc = fitz.open(str(file_path))

    # Extract text from each page
    pages: list[str] = []
    for page in doc:
        # get_text() returns the text layer of one page
        # It preserves the reading order of the PDF content streams
        page_text = page.get_text()
        pages.append(page_text)

    # Always close the document to free resources
    doc.close()

    # Join all pages with double-newline separators
    full_text = "\n\n".join(pages)

    # Clean up the text (remove PDF extraction artifacts)
    full_text = _clean_text(full_text)

    # Also clean individual pages for consistency
    pages = [_clean_text(p) for p in pages]

    return full_text, pages, len(pages)


def extract_text_from_txt(file_path: Path) -> tuple[str, list[str], int]:
    """
    Extract text from a plain text file.

    Simple: just read the file and clean it.
    Plain text files are always "1 page".

    Args:
        file_path: Path to the .txt file.

    Returns:
        (full_text, [full_text], 1)
    """
    raw_text = file_path.read_text(encoding="utf-8")
    cleaned = _clean_text(raw_text)
    return cleaned, [cleaned], 1


# ═══════════════════════════════════════════════════════════════════════════
# PRIVATE HELPERS
# ═══════════════════════════════════════════════════════════════════════════


def _clean_text(text: str) -> str:
    """
    Normalize extracted text to remove common PDF extraction artifacts.

    PDF text extraction typically produces:
      - Excessive blank lines (3, 4, 5 consecutive newlines)
      - Trailing whitespace on lines
      - Multiple consecutive spaces (from column layouts)

    This function fixes all three issues.

    Steps:
      1. Strip trailing whitespace from each line
      2. Collapse 3+ consecutive newlines into exactly 2 (one blank line)
      3. Collapse multiple spaces into a single space
      4. Strip leading/trailing whitespace from the whole text

    Example:
        Input:  "Hello   World  \\n\\n\\n\\nGoodbye  "
        Output: "Hello World\\n\\nGoodbye"
    """
    # Step 1: Strip trailing whitespace on each line
    #   "Hello   \n"  →  "Hello\n"
    text = "\n".join(line.rstrip() for line in text.splitlines())

    # Step 2: Collapse 3+ newlines into exactly 2
    #   "\n\n\n\n"  →  "\n\n"
    #   This preserves paragraph breaks (double newline) but removes
    #   excessive gaps that PDF extraction often creates
    text = re.sub(r"\n{3,}", "\n\n", text)

    # Step 3: Collapse multiple spaces into one
    #   "Hello     World"  →  "Hello World"
    #   PDF column layouts often produce extra spaces
    text = re.sub(r" {2,}", " ", text)

    # Step 4: Strip leading/trailing whitespace from the entire text
    return text.strip()